name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Create handout beamer
        run: |

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: appunti/appunti.tex
          root_file: presentazione/presentazione.tex
          root_file: presentazione/presentazione-handout.tex
      - name: Move compiled files
        run: |
          mkdir outputs/
          mv appunti.pdf outputs/appunti.pdf
          mv presentazione.pdf outputs/presentazione.pdf
          mv presentazione-handout.pdf outputs/presentazione-handout.pdf
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-documents
          path: outputs/
