name: Build LaTeX documents
on: [push]
jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt
      - name: Test oCP =/= cond. non-signalling
        run: |
          python script/cond_non-sign__oCP.py
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Create handout beamer source
        run: |
          cd presentazione
          ./create_handout
          cd ..
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            appunti/appunti.tex
            presentazione/presentazione.tex
            presentazione/presentazione-handout.tex
      - name: Move compiled files
        run: |
          mkdir outputs/
          mv appunti.pdf outputs/appunti.pdf
          mv presentazione.pdf outputs/presentazione.pdf
          mv presentazione-handout.pdf outputs/presentazione-handout.pdf
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-documents
          path: outputs/

  send_to_server:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: compiled-documents
          path: .
      - name: Install SSH & tools
        run: |
          apt-get install -y sshpass
          apt-get install -y ssh
      - name: Upload artifacts
        env:
          SSHUSER: ${{ secrets.SSHUSER }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
          SSHPATH: ${{ secrets.SSHPATH }}
          SSHPASS: ${{ secrets.SSHPASS }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no appunti.pdf $SSHUSER@$SSHSERVER:$SSHPATH
          sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no presentazione-handout.pdf $SSHUSER@$SSHSERVER:$SSHPATH
          sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no presentazione.pdf $SSHUSER@$SSHSERVER:$SSHPATH
